Repository AY2021S2-CS2103T-W10-4/tp, pull requests merged in 2021-03, with the labels that each got.

#124 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/FindStudentSequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/tracing/FindCommandSequenceDiagram.puml
  docs/images/FindStudentActivityDiagram.png
  docs/images/FindStudentSequenceDiagram.png
  docs/images/StorageClassDiagram.png
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: DG

#125 Update find command
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/MatriculationNumberContainsKeywordsPredicate.java
Labels: Assertions, Logging

#127 Add assertions for the parsing of Delete Command
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
Labels: Assertions

#131 Add assertion for add appointment args length
  build.gradle
  src/main/java/seedu/student/logic/parser/AddAppointmentCommandParser.java
Labels: Assertions

#158 Fix bug with deletion of student
  src/main/java/seedu/student/logic/commands/DeleteStudentCommand.java
  src/main/java/seedu/student/model/StudentBook.java
  src/main/java/seedu/student/model/appointment/SameDateAppointmentList.java
  src/main/java/seedu/student/model/appointment/UniqueAppointmentList.java
  src/test/java/seedu/student/logic/commands/DeleteStudentCommandTest.java
Labels: bug
